[build]
  publish = "public"

[context.deploy-preview]
  [context.production.environment]
  HUGO_VERSION = "v0.33"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview.environment]
  HUGO_VERSION = "v0.33"